export type Service = { title:string; eyebrow:string; intro:string; answer:string; image:string; benefits:string[]; steps:string[]; faq:[string,string][]; imageAlt?:string };

export const services:Record<string,Service> = {
  "car-key-programming-colombo": { title:"Car Key Programming in Colombo", eyebrow:"Vehicle key specialists", intro:"Mobile car key programming for transponder keys, remote fobs and proximity smart keys across Colombo and nearby suburbs.", answer:"KeyHome provides car key programming and lost car key programming for many Japanese, European and Korean vehicles. Send the make, model, year and current key status to confirm compatibility.", image:"/images/optimized/service-programming.webp", benefits:["Transponder chip programming","Remote and smart-key programming","All-keys-lost support where available","Mobile service subject to availability"], steps:["Share your vehicle details","We confirm support and availability","A technician cuts or programs the key","Test every key and remote function"], faq:[["Can you program a key without the original?","For many vehicles, yes. The exact method depends on the immobilizer system and whether every key is lost."],["Which vehicle brands do you support?","We support many popular makes. Compatibility varies by model and year, so contact us with the registration details."],["Is car key programming available near me in Colombo?","Mobile car key programming is available in Colombo, Maharagama and nearby areas, subject to equipment and technician availability. Share your location and vehicle details to confirm coverage."]] },
  "car-key-replacement-colombo": { title:"Car Key Replacement in Colombo", eyebrow:"Lost or damaged keys", intro:"Replacement car keys cut and programmed for drivers across Colombo, including spare-key and all-keys-lost situations.", answer:"KeyHome can replace many lost, broken or worn vehicle keys. We identify the correct key type, cut the blade where required and program the transponder or remote to the vehicle.", image:"/images/optimized/gallery-3.webp", imageAlt:"Remote key beside a Toyota Vitz", benefits:["Lost-key replacement","Spare car key duplication","Broken or worn key replacement","Remote and transponder options"], steps:["Tell us the make, model and year","Confirm ownership and key type","Cut and program the replacement","Test starting, locking and remote functions"], faq:[["Can you replace a completely lost car key?","Often, yes. Availability depends on the vehicle and immobilizer system."],["Should I replace or repair my key?","We inspect the key and remote first, then explain whether repair or replacement is the better option."],["What should I bring?","Bring the vehicle and proof that you are authorized to request key work."]] },
  "emergency-car-unlocking": { title:"Car Door Unlock Service in Colombo", eyebrow:"24/7 lockout assistance", intro:"Keys locked in your car? Contact KeyHome for mobile car door unlock services in Colombo and nearby suburbs.", answer:"For an urgent car lockout, call KeyHome with your location, vehicle make and model. Our car door unlock service focuses on careful entry. Avoid forcing the window or lock, which may cause more expensive damage.", image:"/images/optimized/service-emergency.webp", benefits:["24-hour telephone response","Mobile assistance across Colombo","Vehicle-specific entry approach","Clear information before attendance"], steps:["Call and share your location","Describe the vehicle and situation","Confirm ownership when requested","Technician assesses and opens the vehicle"], faq:[["Can you open my car without damage?","Our technicians choose specialist methods for the vehicle and prioritize careful, damage-conscious entry."],["Who should I call when my keys are locked in the car?","Call KeyHome with your location and vehicle model. We can confirm whether a mobile technician is available for car door unlocking near you."],["Which areas do you cover?","Coverage includes Colombo, Maharagama and nearby suburbs, subject to technician availability."]] },
  "smart-key-repair": { title:"Smart Key Repair & Programming in Colombo", eyebrow:"Remote and proximity keys", intro:"Smart key programming, diagnosis and repair for proximity keys, key fobs and transponder keys in Colombo.", answer:"A smart key that no longer locks, unlocks or starts the vehicle may have a battery, button, casing, circuit or programming fault. KeyHome diagnoses the problem before recommending smart key repair, programming or replacement.", image:"/images/optimized/gallery-10.webp", imageAlt:"Two smart-key fobs beside a Suzuki Wagon R", benefits:["Smart-key fault diagnosis","Remote button and casing assessment","Smart key and transponder programming","Replacement options when repair is unsuitable"], steps:["Describe the symptoms","We inspect the key and vehicle response","Approve the recommended solution","Test all repaired or programmed functions"], faq:[["Why did my smart key stop working?","Common causes include a weak battery, worn buttons, casing damage, circuit faults or lost synchronization."],["Can every smart key be repaired?","No. Repairability depends on the damage and availability of compatible parts."],["Can you program a replacement key fob?","We program compatible remotes and smart keys for many vehicle models. Share your make, model and year to confirm support."]] },
  "key-cutting-maharagama": { title:"Key Cutting in Colombo & Maharagama", eyebrow:"Car and general key duplication", intro:"Key cutting in Colombo for car keys, spare keys and supported general keys. Visit KeyHome in Maharagama or ask about mobile automotive service availability.", answer:"KeyHome cuts duplicate and replacement keys at its Maharagama location in the Colombo area. For car keys with a transponder or remote, cutting the metal blade is only one step: programming may also be needed before the key starts the vehicle.", image:"/images/optimized/gallery-18.webp", imageAlt:"Vehicle key blade beside a key-cutting machine", benefits:["Car key cutting and blade replacement","Spare and duplicate keys","General key cutting for supported blanks","Transponder programming when required"], steps:["Tell us the key type or vehicle model","Bring the original key when available","We identify a compatible blank and cut it","Test the key and program it if required"], faq:[["Can you cut house keys as well as car keys?","KeyHome offers general and automotive key cutting in Maharagama. Call with your key type first so we can confirm a compatible blank is available."],["Can you copy a car key with a chip?","For many supported models, yes, but the new transponder must also be programmed to the vehicle before it can start the engine."],["Can a worn key be duplicated?","We first assess the wear because copying a badly worn profile may reproduce the problem."],["Where can I get key cutting in Colombo?","KeyHome is based in Maharagama in the Colombo area. Call before visiting to confirm the key type and availability; ask whether mobile automotive assistance is available for your location."]] },
  "toyota-key-programming": { title:"Toyota Key Programming in Colombo", eyebrow:"Toyota smart-key support", intro:"Toyota transponder key, remote and smart-key programming for supported models in Colombo.", answer:"KeyHome provides Toyota key programming for many supported models. The correct process depends on the model, year, key type and whether a working key remains.", image:"/images/optimized/gallery-7.webp", imageAlt:"Two Toyota smart-key fobs inside a Toyota vehicle", benefits:["Toyota transponder keys","Remote fob programming","Proximity smart keys","All-keys-lost assessment"], steps:["Share the Toyota model and year","Send a photo of the current key if available","Confirm the correct key solution","Cut, program and fully test the key"], faq:[["Can you program a Toyota key when all keys are lost?","This is possible for many models, subject to the vehicle system and key availability."],["Do you support Toyota smart keys?","We support many Toyota proximity and remote-key systems. Contact us to confirm your exact model and year."],["Will the emergency blade also be cut?","Where the key design includes a blade, cutting can be included as part of the replacement process."]] }
};

services["lock-repair-colombo"] = {
  title: "Car Lock Repair in Colombo", eyebrow: "Vehicle lock and key faults",
  intro: "Help with sticking car locks, worn keys and ignition key problems in Colombo and nearby suburbs.",
  answer: "KeyHome assesses vehicle key and lock faults before recommending repair or replacement. Share your vehicle details and describe what happens when you use the key so we can confirm the right next step.",
  image: "/images/optimized/service-auto.webp",
  benefits: ["Vehicle door-lock fault assessment", "Worn or damaged key assessment", "Broken-key assistance where supported", "Repair or replacement options explained"],
  steps: ["Describe the vehicle and fault", "Confirm an assessment appointment", "Review the recommended work", "Test the repaired key or lock"],
  faq: [
    ["Should I force a key that will not turn?", "No. Stop applying pressure and contact us with the symptoms. Forcing a key can damage the blade or lock."],
    ["Can every car lock be repaired?", "Repair depends on the fault, condition and compatible parts. A replacement may be more suitable in some cases."],
    ["Do you also help with household lockouts?", "Yes. KeyHome offers household door unlocking as a separate service. Tell us which type of door and lock is affected when you call."],
  ],
};

services["door-unlocking-colombo"] = {
  title: "Household Door Unlocking in Colombo", eyebrow: "Locked out of home?",
  intro: "Contact KeyHome for household door unlocking in Colombo and nearby suburbs. Call with your location and lock details to confirm assistance.",
  answer: "KeyHome provides household door-unlocking assistance as well as car unlocking. We assess the door, lock and situation before recommending an entry method. Authorization to access the property must be confirmed.",
  image: "/images/optimized/logo.webp",
  benefits: ["Household lockout assessment", "Door and lock type checked before work", "Access only with appropriate authorization", "Attendance and scope confirmed by phone"],
  steps: ["Call with your location", "Describe the door and lock", "Confirm authorization and proposed work", "Check the door operation after access"],
  faq: [
    ["What should I tell you when I call?", "Share your location, the type of door and lock, and whether the key is lost, inside the property or broken. You can send a photo of the lock through WhatsApp."],
    ["Can you guarantee the lock will not need replacing?", "No. The method and repair needs depend on the lock and its condition. The technician should explain the proposed approach before starting."],
    ["What proof of authorization is required?", "Be prepared to show that you live at the property or have the owner’s permission. Confirm the appropriate documents when booking."],
  ],
};
