import "./App.css";

const phone = "+94774380935";

type Service = { title:string; eyebrow:string; intro:string; answer:string; image:string; benefits:string[]; steps:string[]; faq:[string,string][] };

const services:Record<string,Service> = {
  "car-key-programming-colombo": { title:"Car Key Programming in Colombo", eyebrow:"Vehicle key specialists", intro:"Programming for transponder keys, remote fobs and proximity smart keys across Colombo and nearby suburbs.", answer:"KeyHome provides car key programming in Colombo for many Japanese, European and Korean vehicles. Send the make, model, year and current key status to confirm compatibility.", image:"/images/optimized/service-programming.webp", benefits:["Transponder chip programming","Remote and smart-key setup","All-keys-lost support where available","Mobile service subject to availability"], steps:["Share your vehicle details","We confirm support and availability","A technician cuts or programs the key","Test every key and remote function"], faq:[["Can you program a key without the original?","For many vehicles, yes. The exact method depends on the immobilizer system and whether every key is lost."],["Which vehicle brands do you support?","We support many popular makes. Compatibility varies by model and year, so contact us with the registration details."],["Do you provide mobile programming?","Mobile car key programming is available in Colombo and nearby areas subject to equipment and technician availability."]] },
  "car-key-replacement-colombo": { title:"Car Key Replacement in Colombo", eyebrow:"Lost or damaged keys", intro:"Replacement car keys cut and programmed for drivers across Colombo, including spare-key and all-keys-lost situations.", answer:"KeyHome can replace many lost, broken or worn vehicle keys. We identify the correct key type, cut the blade where required and program the transponder or remote to the vehicle.", image:"/images/optimized/gallery-3.webp", benefits:["Lost-key replacement","Spare car key duplication","Broken or worn key replacement","Remote and transponder options"], steps:["Tell us the make, model and year","Confirm ownership and key type","Cut and program the replacement","Test starting, locking and remote functions"], faq:[["Can you replace a completely lost car key?","Often, yes. Availability depends on the vehicle and immobilizer system."],["Should I replace or repair my key?","We inspect the key and remote first, then explain whether repair or replacement is the better option."],["What should I bring?","Bring the vehicle and proof that you are authorized to request key work."]] },
  "emergency-car-unlocking": { title:"Emergency Car Unlocking in Colombo", eyebrow:"24/7 lockout assistance", intro:"Locked your key inside the vehicle? Contact KeyHome for careful mobile car door unlocking assistance.", answer:"For an urgent car lockout, call KeyHome with your location, vehicle make and model. Avoid forcing the window or lock, which may cause more expensive damage.", image:"/images/optimized/service-emergency.webp", benefits:["24-hour telephone response","Mobile assistance across Colombo","Vehicle-specific entry approach","Clear information before attendance"], steps:["Call and share your location","Describe the vehicle and situation","Confirm ownership when requested","Technician assesses and opens the vehicle"], faq:[["Can you open my car without damage?","Our technicians choose specialist methods for the vehicle and prioritize careful, damage-conscious entry."],["What information do you need?","We need your location, vehicle make and model, and a description of where the key is."],["Which areas do you cover?","Coverage includes Colombo, Maharagama and nearby suburbs, subject to technician availability."]] },
  "smart-key-repair": { title:"Smart Key Repair & Programming", eyebrow:"Remote and proximity keys", intro:"Diagnosis, repair and programming for smart keys, remote fobs and transponder keys in Colombo.", answer:"A smart key that no longer locks, unlocks or starts the vehicle may have a battery, button, casing, circuit or programming fault. KeyHome diagnoses the problem before recommending repair or replacement.", image:"/images/optimized/gallery-10.webp", benefits:["Smart-key fault diagnosis","Remote button and casing assessment","Transponder programming","Replacement options when repair is unsuitable"], steps:["Describe the symptoms","We inspect the key and vehicle response","Approve the recommended solution","Test all repaired or programmed functions"], faq:[["Why did my smart key stop working?","Common causes include a weak battery, worn buttons, casing damage, circuit faults or lost synchronization."],["Can every smart key be repaired?","No. Repairability depends on the damage and availability of compatible parts."],["Can you program a replacement remote?","We program compatible remotes and smart keys for many vehicle models."]] },
  "key-cutting-maharagama": { title:"Key Cutting in Maharagama", eyebrow:"Precision duplication", intro:"Convenient automotive and general key cutting and duplication from KeyHome in Maharagama.", answer:"KeyHome cuts duplicate and replacement keys in Maharagama. Automotive keys may also require transponder or remote programming before they can start and operate the vehicle.", image:"/images/optimized/gallery-1.webp", benefits:["Automotive key cutting","Spare-key duplication","Replacement key blades","Programming where required"], steps:["Bring the original key when available","We identify the correct blank","Cut the new key accurately","Test fit and program if required"], faq:[["Can you copy a car key with a chip?","Yes, for many models, but the new transponder must also be programmed to the vehicle."],["Can a worn key be duplicated?","We first assess the wear because copying a badly worn profile may reproduce the problem."],["Where are you located?","KeyHome is based in Maharagama, Colombo. Call before visiting for availability."]] },
  "toyota-key-programming": { title:"Toyota Key Programming in Colombo", eyebrow:"Toyota smart-key support", intro:"Toyota transponder key, remote and smart-key programming for supported models in Colombo.", answer:"KeyHome provides Toyota key programming for many supported models. The correct process depends on the model, year, key type and whether a working key remains.", image:"/images/optimized/gallery-29.webp", benefits:["Toyota transponder keys","Remote fob programming","Proximity smart keys","All-keys-lost assessment"], steps:["Share the Toyota model and year","Send a photo of the current key if available","Confirm the correct key solution","Cut, program and fully test the key"], faq:[["Can you program a Toyota key when all keys are lost?","This is possible for many models, subject to the vehicle system and key availability."],["Do you support Toyota smart keys?","We support many Toyota proximity and remote-key systems. Contact us to confirm your exact model and year."],["Will the emergency blade also be cut?","Where the key design includes a blade, cutting can be included as part of the replacement process."]] }
};

export default function ServicePage(){
  const slug=location.pathname.split("/").filter(Boolean)[0] || "car-key-programming-colombo";
  const service=services[slug] || services["car-key-programming-colombo"];
  const whatsapp=`https://wa.me/${phone}?text=${encodeURIComponent(`Hello KeyHome, I need help with ${service.title}.`)}`;
  return <><div className="topbar"><div className="shell topbar-inner"><span><span className="status-dot"/>Available 24 hours, 7 days a week</span><a href={`tel:${phone}`}>Emergency: +94 77 438 0935</a></div></div><header className="site-header"><div className="shell nav-wrap"><a className="brand" href="/"><img src="/images/optimized/logo.webp" width="52" height="52" alt=""/><span><b>KEYHOME</b><small>LOCKSMITH SPECIALISTS</small></span></a><nav className="nav service-nav"><a href="/#services">All services</a><a href="/#work">Our work</a><a href="/#contact">Contact</a><a className="nav-cta" href={`tel:${phone}`}>Call now</a></nav></div></header><main><section className="service-hero"><div className="shell service-hero-grid"><div><p className="eyebrow"><span/>{service.eyebrow}</p><h1>{service.title}</h1><p>{service.intro}</p><div className="hero-actions"><a className="button primary" href={`tel:${phone}`}>Call +94 77 438 0935</a><a className="button secondary" href={whatsapp}>WhatsApp us</a></div></div><img src={service.image} width="560" height="420" alt="KeyHome automotive locksmith service"/></div></section><section className="service-answer"><div className="shell narrow"><p className="kicker">Quick answer</p><h2>How can KeyHome help?</h2><p>{service.answer}</p></div></section><section className="section"><div className="shell service-detail-grid"><div><p className="kicker">What is included</p><h2>Professional help for your vehicle key.</h2><ul className="benefit-list">{service.benefits.map(x=><li key={x}>✓ {x}</li>)}</ul></div><div className="process-card"><p className="kicker light">Simple process</p>{service.steps.map((x,i)=><div key={x}><strong>0{i+1}</strong><span>{x}</span></div>)}</div></div></section><section className="section faq"><div className="shell faq-grid"><div><p className="kicker">Common questions</p><h2>{service.title} FAQs</h2></div><div className="faq-list">{service.faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section><section className="service-cta"><div className="shell"><h2>Need help with your key today?</h2><p>Call KeyHome for availability and a solution suited to your vehicle.</p><a className="button primary" href={`tel:${phone}`}>Call +94 77 438 0935</a></div></section></main><footer><div className="shell copyright"><span>© {new Date().getFullYear()} KeyHome.</span><a href="/">Return to homepage</a></div></footer><a className="floating-whatsapp" href={whatsapp} aria-label="Chat with KeyHome on WhatsApp"><span>WhatsApp</span></a></>;
}
